#!/bin/sh
DACHO_HOME=$(pwd)/..
if [ -z $JAVA_HOME ]; then
 echo "JAVA_HOME needs to be set"
 exit
fi
JAVA_PATH=$JAVA_HOME/bin/java
JCONSOLE_OPTS="-Dcom.sun.management.jmxremote.port=9005 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
$JAVA_PATH $JCONSOLE_OPTS -Dxml.config=$DACHO_HOME/config/dacho.xml -Ddacho.home=$DACHO_HOME -Djava.util.logging.config.file=$DACHO_HOME/config/logging.properties -server -jar $DACHO_HOME/lib/dacho-service-manager-1.0.jar
